---
# installing ansible
- name: Add ansible repository
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present

- name: install ansible
  apt: name=ansible state=present update_cache=yes
