---
# installing gradle
- name: Download gradle
  get_url:
    url: "https://services.gradle.org/distributions/gradle-{{gradle_version}}-bin.zip"
    dest: /tmp/gradle-{{gradle_version}}-bin.zip

- name: add /opt/gradle directory
  file:
    path: /opt/gradle
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Unpack the compressed Gradle
  unarchive:
    src: /tmp/gradle-{{gradle_version}}-bin.zip
    dest: /opt/gradle
    remote_src: true

- name: Add gradle directory to global $PATH.
  template:
    src: gradle.sh.j2
    dest: /etc/profile.d/gradle.sh
    mode: 0644


- name: remove downloaded zip
  file:
    path: /tmp/gradle-{{gradle_version}}-bin.zip
    state: absent
