---
- name: add jenkins .ssh directory
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: add jenkins public key
  copy: content="{{ lookup('file', './files/keys/jenkins.pub') }}" dest=/var/lib/jenkins/.ssh/id_rsa.pub mode=644 owner=jenkins group=jenkins
  when: jenkins_flag
  tags: jenkins

- name: add jenkins private key
  copy: content="{{ lookup('file', './files/keys/jenkins.priv') }}" dest=/var/lib/jenkins/.ssh/id_rsa mode=600 owner=jenkins group=jenkins
  when: jenkins_flag
  tags: jenkins
