---
- name: common utilites
  include: utilities.yml

- name: jenkins post installation tasks
  include: jenkins-post.yml
  when: jenkins_flag
  tags: jenkins

- name: get gradle directory
  stat:
    path: /opt/gradle/gradle-{{gradle_version}}
  register: gradle_result
  tags: gradle

#- debug:
#    var: gradle_result
#  tags: gradle

- name: install gradle
  include: gradle.yml
  when: gradle_flag and not gradle_result.stat.exists
  tags: gradle

- name: install ansible
  include: ansible.yml
  when: ansible_flag
  tags: ansible
