---
- name: add block for docker container outgoing connections 
  blockinfile:
    name: /etc/ufw/before.rules
    insertbefore: "# Don't delete these required lines, otherwise there will be errors"
    content: |
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING ! -o docker0 -s 172.17.0.0/16 -j MASQUERADE
      COMMIT

