---
- hosts: all
  remote_user: root
  vars:
    ansible_user_keys:
    - key: "{{ lookup('file', './files/keys/ansible.pub') }}"
    - key: "{{ lookup('file', './files/keys/my.pub') }}"
    #- key: "{{ lookup('file', './files/keys/ove.pub') }}"
    sudo_users:
    - name: ansible
      nopasswd: yes

  tasks:
  - name: create user
    user: name=ansible comment="Ansible" shell=/bin/bash state=present

  - name: add ssh authorized_keys
    authorized_key: user=ansible state=present unique=true key="{{ item.key }}"
    with_items: "{{ ansible_user_keys }}"

  - name: add ansible public key
    copy: content="{{ lookup('file', './files/keys/ansible.pub') }}" dest=/home/ansible/.ssh/id_rsa.pub mode=644 owner=ansible group=ansible
    when: ansible_keys_flag

  - name: add ansible private key
    copy: content="{{ lookup('file', './files/keys/ansible.priv') }}" dest=/home/ansible/.ssh/id_rsa mode=600 owner=ansible group=ansible
    when: ansible_keys_flag

  roles:
  - {role: franklinkim.sudo}
