---
- hosts: all
  become: yes
  roles:
    - {role: kamaln7.swapfile,      when: swap_flag,     tags: swap}
    - {role: willshersystems.sshd,                       tags: sshd}
    - {role: geerlingguy.java,      when: java_flag,     tags: java}
    - {role: geerlingguy.jenkins,   when: jenkins_flag,  tags: jenkins}
    - {role: geerlingguy.nodejs,    when: nodejs_flag,   tags: nodejs}
    - {role: ANXS.postgresql,       when: postgres_flag, tags: postgres}
    - {role: geerlingguy.nginx,     when: nginx_flag,    tags: nginx}
    - {role: andrewrothstein.terraform, when: terraform_flag, tags: terraform}
    - {role: williamyeh.prometheus, when: prometheus_flag, tags: prometheus}
    - {role: geerlingguy.docker,    when: docker_flag,   tags: docker}
    - {role: openmicroscopy.cadvisor, when: docker_flag, tags: cadvisor}
    - {role: ssilab.aws-cli,        when: awscli_flag,   tags: awscli}
    - {role: common-post                                           }
