---
- hosts: all
  become: yes
  roles:
    - {role: willshersystems.sshd,                      tags: sshd}
    - {role: franklinkim.ufw,                           tags: ufw}
    - {role: geerlingguy.java,      when: java_flag,    tags: java}
    - {role: geerlingguy.jenkins,   when: jenkins_flag, tags: jenkins}

  tasks:
  - name: add jenkins public key
    copy: content="{{ lookup('file', './files/keys/jenkisn.pub') }}" dest=/var/lib/jenkins/.ssh/id_rsa.pub mode=644 owner=ansible
    when: jenkins_flag

  - name: add jenkins private key
    copy: content="{{ lookup('file', './files/keys/jenkins.priv') }}" dest=/var/lib/jenkins/.ssh/id_rsa mode=600 owner=ansible
    when: jenkins_flag
