---
- hosts: all
  become: yes

  tasks:
  - name: install docker-engine
    script: ./files/scripts/install_docker_ubuntu16.04.sh
    when: docker_flag
    tags: docker

  - name: fix ufw/docker conflict
    copy: content="{{ lookup('file', './files/etc/daemon.json') }}" dest=/etc/docker/daemon.json mode=644 owner=docker group=docker
    when: docker_flag
    tags: docker

  - name: install docker-compose
    script: ./files/scripts/install_docker_compose_ubuntu16.04.sh
    when: docker_flag
    tags: docker

  - name: install docker-machine
    script: ./files/scripts/install_docker_machine_ubuntu16.04.sh
    when: docker_flag
    tags: docker

  - name: add docker group
    group:
      name: docker
      state: present
    when: docker_flag
    tags: docker

  - name: add jenkins user to docker group
    user:
      name: jenkins
      groups: docker
      append: yes
    when: docker_flag and jenkins_flag
    tags: docker

  - name: add ansible user to docker group
    user:
      name: ansible
      groups: docker
      append: yes
    when: docker_flag
    tags: docker
